# Example _config.yml
title: Surbhi's Portfolio
description: My projects and achievements
# theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
